# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50230ee9153812209df394b7a95a2c27f7951a166ca9cc5a9527fe51d5568d269b9dd7d6b289e0c1cfeaf031c42bd2b45435c3ebeb579ce92195ef409dc294d7

test:
  secret_key_base: 607dc42b381644cfb75d4aa42826831b903db46ca7a560009cd3da45875dd4c71a2816727eb81ce51249dce6f114454ad2d9c0ad15ec7792444da73d6662f58a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
